README
tatsuo1981/graduation_project pull request #1
Opened 2024-08-24 10:01 UTC by tatsuo1981

README

■サービス概要
どんなサービスなのかを３行で説明してください。
関西の生ビール(ビール全般、発泡酒含む)が安い店を投稿(神泡画像投稿)、いいね、ハッピーアワー時間通知してくれる
ユーザー様に安い店を投稿してもらうアプリ
■ このサービスへの思い・作りたい理由
このサービスの題材となるものに関してのエピソードがあれば詳しく教えてください。

このサービスを思いつくにあたって元となる思いがあれば詳しく教えてください。

私自身がビールの価格が安い店を頻繁に検索していますが中々探すのに苦労しています、自分が検索したお店を掲載し見つけやすくするそんなアプリが有ればいいなと思いました。

■ ユーザー層について
決めたユーザー層についてどうしてその層を対象にしたのかそれぞれ理由を教えてください。

成人全般、お酒を嗜む方
層が幅広いので利用してくれそうだから

■サービスの利用イメージ
ユーザーがこのサービスをどのように利用できて、それによってどんな価値を得られるかを簡単に説明してください。

みんなにビールを安く飲んでもらいたい、ハッピーアワー時間が通知されてより安く生ビール(ビール)が飲める

■ ユーザーの獲得について
想定したユーザー層に対してそれぞれどのようにサービスを届けるのか現状考えていることがあれば教えてください。
美味しそうなビール画像の提供　ハッピーアワー時間の通知

■ サービスの差別化ポイント・推しポイント
似たようなサービスが存在する場合、そのサービスとの明確な差別化ポイントとその差別化ポイントのどこが優れているのか教えてください。
独自性の強いサービスの場合、このサービスの推しとなるポイントを教えてください。

神泡投稿(神泡とは飲食店様や個人様それぞれのこだわりの注ぎ方で実現した「きめ細やかでクリーミーな泡)
また、お気に入り登録店舗のハッピーアワー時間掲載、投稿(ハッピーアワーとはレストランやバーなどの飲食店が酒類を行う時間、一般的に利用者が少ない平日の16時から19時ごろに実施)

■ 機能候補
現状作ろうと思っている機能、案段階の機能をしっかりと固まっていなくても構わないのでMVPリリース時に作っていたいもの、本リリースまでに作っていたいものをそれぞれ分けて教えてください。
ログイン、安いお店の投稿(神泡投稿含む)、いいね、お気に入り登録、ハッピーアワー時間通知

■ 機能の実装方針予定
一般的なCRUD以外の実装予定の機能についてそれぞれどのようなイメージ(使用するAPIや)で実装する予定なのか現状考えているもので良いので教えて下さい。

よろしくお願いします。

2024-08-25 08:20 UTC, tarakish requested changes
確認しました。以下コメントです！

---

- ユーザーの獲得について
  - こちらは訪れたユーザーをどう保持するか、というよりはターゲットユーザーをどのようにサービスに誘導するか、という目線で考えてみてください。

- こちらのPullRequestはREADMEのレビューのため、不要なファイルは含めないようにしましょう！

- 各項目の説明文（`どんなサービスなのかを３行で説明してください。`）は不要なので削除するようにお願いします

2024-08-29 04:38 UTC, tatsuo1981 commented
# README
■サービス概要
関西の生ビール(ビール全般、発泡酒含む)が安い店を投稿(神泡画像投稿)、いいね、ハッピーアワー時間通知してくれる
ユーザー様に安い店を投稿してもらうアプリ

■ このサービスへの思い・作りたい理由
私自身がビールの価格が安い店を頻繁に検索していますが中々探すのに苦労しています、自分が検索したお店を掲載し見つけやすくするそんなアプリが有ればいいなと思いました。

■ ユーザー層について
成人全般、お酒を嗜む方
層が幅広いので利用してくれそうだから

■サービスの利用イメージ
みんなにビールを安く飲んでもらいたい、ハッピーアワー時間が通知されてより安く生ビール(ビール)が飲める

■ ユーザーの獲得について
インパクトのあるキャッチコピーを使ってサービスに誘導する

■ サービスの差別化ポイント・推しポイント
神泡投稿(神泡とは飲食店様や個人様それぞれのこだわりの注ぎ方で実現した「きめ細やかでクリーミーな泡)
また、お気に入り登録店舗のハッピーアワー時間掲載、投稿(ハッピーアワーとはレストランやバーなどの飲食店が酒類を行う時間、一般的に利用者が少ない平日の16時から19時ごろに実施)

■ 機能候補
ログイン、安いお店の投稿(神泡投稿含む)、いいね、お気に入り登録、ハッピーアワー時間通知

■ 機能の実装方針予定
一般的なCRUD以外の実装予定の機能についてそれぞれどのようなイメージ(使用するAPIや)で実装する予定なのか現状考えているもので良いので教えて下さい。

2024-08-29 06:16 UTC, TakenakaEri commented
確認ありがとうございます！

ハッピーアワーの時間の通知を行うとのことですが、どのような通知方法を検討されていますか？
（LINE通知などでしょうか？）

また、初期の状態で多少でも良いので、データが入っていないと、「登録してみようかな」と思わせることが難しいと思うのですが、既にデータはお持ちでしょうか？（ご自身で実際に行ったお店の値段や写真があればそれで大丈夫です）

ご確認お願いします。

2024-08-30 08:03 UTC, tatsuo1981 commented
lineでの実装を考えていますが、今から１ヶ月で実装できるかわからないので後から実装します
お店の登録はユーザー様にも協力してもらい登録店を増やすシステムです。
私も行ったお店調べたお店を掲載します

2024-08-30 12:14 UTC, rdhdchloe commented
ご対応ありがとうございます。
以下コメントになります。

---

■ ユーザー層について
成人全般、お酒を嗜む方
層が幅広いので利用してくれそうだから
→ ユーザー層を広すぎるので絞っていただきたいです。


■ ユーザーの獲得について
インパクトのあるキャッチコピーを使ってサービスに誘導する
→ インパクトのあるは少し曖昧です。追記していただきたいです。
→ キャッチコピーはどこに載せる予定ですか？

■ 機能の実装方針予定
→ 追記していただきたいです。


宜しくお願い致します。

2024-09-02 01:16 UTC, tatsuo1981 commented
■サービス概要
関西の生ビール(ビール全般、発泡酒含む)が安い店を投稿(神泡画像投稿)、いいね、ハッピーアワー時間通知してくれるユーザー
様に安い店を投稿してもらえるアプリ

■ このサービスへの思い・作りたい理由
私自身がビールの価格が安い店を頻繁に検索していますが中々探すのに苦労しています、自分が検索したお店を掲載したら簡単に見つかるそんなアプリがあればいいなと思いました。

■ユーザー層について
２０代から５０代、お酒を好む方
その中で仕事終わりの方やお昼のはしご酒、立ち飲み、ちょい飲みを楽しむ方々

■サービスの利用イメージ
みんなにビールを安く飲んでもらいたい、ハッピーアワー時間通知されてより安く生ビールが飲める

■ユーザーの獲得について
検索サイトで検索したときに検索上位に表示
アプリ自体のデザインをシンプルにしてトップ画面に美味しそうなビールの画像
アプリタイトルに激安生麦酒投

■サービスの差別化ポイント・推しポイント
神泡投稿(神泡とは飲食店様や個人様それぞれのこだわりの有料方で実現した「きめ細やかでクリーミーな泡)」また、
お気に入り登録店舗のハッピーアワー時間掲載、投稿(ハッピーアワーとはレストランやバーなどの飲食店が酒類を行う時間、一般的に利用者が少ない平日の16時から19時ごろに実施)

■機能候補
ログイン、安いお店の投稿(神泡投稿含む)、いいね、お気に入り登録、ハッピーアワー時間通知

■ 機能の実装方針予定
ログイン、ユーザー登録、お店登録（神泡投稿）、お気に入り登録、いいね登録、
よろしくお願いします

2024-09-02 07:40 UTC, Tsuchiya2 commented
概ね良いかと思います。LGTMです。

2024-09-03 02:04 UTC, merged